version: "3.7"

services:
  app:
    build: .
    container_name: invest-monitor-app
    restart: always
    ports:
      - "3000:3000"
      - "7000:7000"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres-db:5432/invest_monitor_dev?user=postgres"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: postgres-db
    restart: always
    ports: 
      - "5432:5432"
    volumes:
    - './db:/docker-entrypoint-initdb.d'
