# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: clojure:openjdk-8-lein-2.9.1-slim-buster
        environment:
          DATABASE_URL: "jdbc:postgresql://postgres-db:5432/invest_monitor_test?user=postgres"
      - image: postgres:12-alpine
        name: postgres-db

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: install postgresql-client
          command: |
            apt update
            apt install -y postgresql-client-11

      - run:
          name: create database
          command: |
            psql -h postgres-db -p 5432 -U postgres < db/02-create-test-db.sql

      # run tests!
      - run: lein test