# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#

defaults: &defaults
  docker:
    - image: clojure:openjdk-8-lein-2.9.1-slim-buster
      environment:
        DATABASE_URL: "jdbc:postgresql://postgres-db:5432/invest_monitor_test?user=postgres"
    - image: postgres:12-alpine
      name: postgres-db

  working_directory: ~/repo

  environment:
    LEIN_ROOT: "true"
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

aliases:
  - &restore-cache
    keys:
      - v1-dependencies-{{ checksum "project.clj" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

  - &save-cache
    paths:
      - ~/.m2
    key: v1-dependencies-{{ checksum "project.clj" }}

  - &install-dependencies
    name: install dependencies
    command: lein deps

version: 2.1

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-cache
          
      - run: *install-dependencies
          
      - save_cache: *save-cache

      - run: 
          name: compile
          command: lein compile

  test:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-cache

      - run: *install-dependencies

      - save_cache: *save-cache

      - run:
          name: install postgresql-client
          command: |
            apt update
            apt install -y postgresql-client-11

      - run:
          name: create database
          command: psql -h postgres-db -p 5432 -U postgres < db/02-create-test-db.sql

      - run: 
          name: run tests
          command: lein test

workflows:
  version: 2.1

  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build